# Generated by Django 5.2.2 on 2025-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio_id', models.IntegerField()),
                ('prestamo_id', models.IntegerField()),
                ('costo_adicional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
    ]
