# Generated by Django 5.2.2 on 2025-06-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multa', '0001_initial'),
        ('prestamo', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='prestamo_id',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='socio_id',
        ),
        migrations.AddField(
            model_name='multa',
            name='multa_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='multa',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo'),
        ),
        migrations.AddField(
            model_name='multa',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.socio'),
        ),
    ]
