# Generated by Django 5.2.1 on 2025-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multa', '0002_remove_multa_id_remove_multa_prestamo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multa',
            old_name='multa_ID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='multa',
            name='observacion',
            field=models.TextField(),
        ),
    ]
