# Generated by Django 5.2.1 on 2025-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
