# Generated by Django 5.2.1 on 2025-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='contraseña',
            new_name='contrasena',
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
