# Generated by Django 5.2.2 on 2025-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_rename_contraseña_socio_contrasena_alter_socio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='contrasena',
            new_name='contraseña',
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
