# Generated by Django 5.2.1 on 2025-06-16 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_rename_contrasena_socio_contraseña_alter_socio_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='nombre',
        ),
        migrations.AddField(
            model_name='socio',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socio',
            name='direccion',
            field=models.TextField(blank=True),
        ),
    ]
