# Generated by Django 5.2.1 on 2025-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('libro_id', models.IntegerField()),
                ('socio_id', models.IntegerField()),
                ('prestamo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pretamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'prestamo',
            },
        ),
    ]
