# Generated by Django 5.2.1 on 2025-06-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0002_remove_libro_id_libro_libro_id'),
        ('prestamo', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='socio_id',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.socio'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Libro.libro'),
        ),
    ]
