# Generated by Django 5.2.1 on 2025-06-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_remove_prestamo_socio_id_prestamo_socio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='socio',
            new_name='socio_id',
        ),
    ]
