# Generated by Django 5.2.1 on 2025-06-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0003_rename_socio_prestamo_socio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='prestamo_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='libro_id',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='socio_id',
            new_name='socio',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='costo',
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table=None,
        ),
    ]
