# Generated by Django 5.2.2 on 2025-06-14 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamo', '0004_rename_prestamo_id_prestamo_id_and_more'),
        ('socios', '0003_rename_contrasena_socio_contraseña_alter_socio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_adicional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField()),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
